### ISSUE TITLE
Simple Additional Guides for git

### ISSUE THREAD

**Issue by Jaein-Song** [yatmos/www#53]
This content includes which are not presented in the upload manual.
1. Removing files
You should remove the file both with Linux command and git command (**git rm 'filename'**).

2. Setting a remote repository
you can add a new repository using the command below:
git remote add **repo-name** *https://**user-id**@github.com/**repository**/**name**.git*
in my case, 
**repo-name** is upload
**user id** must be Jaein-Song, the **repository** is Jaein-Song and the **name** is www.
 thus, the command would be,

> git remote add upload https://Jaein-Song@github.com/Jaein-Song/www.git

repository names are stored on the local computer, not online. the names can be shown using the command below,

> git remote show 
This command shows all of the repository names. 
 If you want to see a specific one, use; 
> git remote show repo-name

3. Push the branch
when you are going to push your work to the online repository, you should use 'git push' command.
git push -u **repo-name** "**branchname**"

You have two options for repo-name.
First,  you can use repo-name which set before as written in sect. 2 of this article.
Second, You can use full address whatever you want. like *https://**user-id**@github.com/**repository**/**name**.git*

4. Zsh and Agnoster Theme 
You can use git in a much better environment with zsh.
see http://programmingskills.net/archives/115
you can see the branch and staging status at the command line with zsh agonster theme.
![image](https://user-images.githubusercontent.com/31122430/65483900-cd4a1f80-ded8-11e9-8539-44910a009764.png)

**Comment by hajsong** [comment]
Thank you for the note!
